# Generated by Django 3.0.7 on 2020-06-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=100)),
                ('processor_name', models.CharField(max_length=100)),
                ('processor_clock', models.CharField(max_length=100)),
                ('processor_cores', models.CharField(max_length=100)),
                ('rear_camera', models.CharField(max_length=400)),
                ('front_camera', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('charging_tech', models.CharField(max_length=100)),
                ('launched', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='phones/images')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
